### ISSUE TITLE
Support for more Dronecode autopilot types

### ISSUE THREAD

**Issue by LorenzMeier** [Jace25/LUA-Taranis-Pixhawk#3]
Hi @Jace25 this is a great effort! We have just added support for PX4 to it:
https://github.com/PX4/Firmware/pull/3762

Would you be open to extend your script with the PX4 flight modes? It seems like there is enough space left script and telemetry wise to easily allow that.

We can send you a pull request for it, its more about having your support in accepting such a change upstream.

**Comment by Jace25** [comment]
Hi @LorenzMeier,

i wanted to test PX4 anyway. I'll do that next week and then i will also have a look on the lua Script. If you want you could send a pull request, too
